# Generated by Django 2.1.7 on 2019-04-05 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='profile',
            field=models.OneToOneField(limit_choices_to={'role': 'distributor'}, on_delete=django.db.models.deletion.CASCADE, related_name='distributor', to='med.UserProfile'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='profile',
            field=models.OneToOneField(limit_choices_to={'role': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='retailer', to='med.UserProfile'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='profile',
            field=models.OneToOneField(limit_choices_to={'supplier': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='med.UserProfile'),
        ),
    ]
