# Generated by Django 2.1.7 on 2019-04-05 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_auto_20190405_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='profile',
            field=models.OneToOneField(limit_choices_to={'role': 'supplier'}, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='med.UserProfile'),
        ),
    ]
